title:            Balzac
tagline:          A beautiful theme.
description:      Describe your website.
canonical: http://jekyll.gtat.me
# Name of your site (displayed in the header)
name: Hena Ghonia

# Short bio or description (displayed in the header)
# description: the profile of an engineer, researcher and software developer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: #images/profile.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: henaghonia2015@gmail.com
  facebook:
  flickr:
  github: Hstellar
  instagram:
  linkedin: Hena Ghonia
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: hena_ghonia
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
# excerpt_separator: <!--more-->

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://Hstellar.github.io" # the base hostname & protocol for your site

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/Hstellar
    external: true



# The release of Jekyll Now that you're using
version: v1.2.0

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]



essed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
      - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
    #  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
# plugins:
#   - jekyll-paginate
# Exclude these files from your production _site

